### PR TITLE
Musicplayer

### LINKED ISSUE #6: Music Player
Make a music player using html audio tag.

### PR DESCRIPTION
**Pull request by Ayushparikh-code**
Resolved #6

### CODE REVIEW

**Review by unnati914 — CHANGES_REQUESTED** [review]
I am not able to see the files... kindly check it please

**Comment by Ayushparikh-code** [comment]
> I am not able to see the files... kindly check it, please

plz, review again, files are already added!

**Review by unnati914 — COMMENTED** [review]
cool thanks for contribution ;)

**Comment by Ayushparikh-code** [comment]
> cool thanks for contribution ;)

yeah, calculator and OTHER codxcrypt page files are mixed up so will move them in separate folders!

**Pull request merged**
